# Generated by Django 5.2.1 on 2025-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Groceries', 'GROCERIES'), ('Clothings', 'CLOTHINGS'), ('Electronics', 'ELECTRONICS'), ('Books', 'BOOKS'), ('Furniture', 'FURNITURE'), ('Sports', 'SPORTS'), ('Beauty', 'BEAUTY'), ('Health', 'HEALTH')], max_length=15, null=True),
        ),
    ]
